### ISSUE TITLE
Hide markdown syntax when cursor leaves position 

### ISSUE THREAD

**Issue by erikvlm** [qeude/SwiftDown#13]
Is it possible to have the markdown syntax hide as the cursor leaves the text? Sort of like Obsidian does in their live preview mode?

Eg when writing `**bold**` to only show **bold**? (Notice that the asterisks have been "hidden")

**Comment by qeude** [comment]
Hi @erikvlm, this is not something planned for now.
My idea when building `SwiftDown` was to have a minimalistic way with sort of live preview to write markdown since I'm not a huge fan of stuff like Notion in which you sometimes need to use your mouse to change a node type.
Maybe in the future when `SwiftDown` will be stable enough, we could add two modes
