### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by sergpryimachuk** [qeude/SwiftDown#25]
Hey, I was happy to find this package and wanted to try it in my project. However, I faced some warnings that intrigue me.

**Describe the bug**
When installing the package, Xcode asks for Keychain access. And then, after refusing it, it shows up the error:

>`Build plug-ins with malicious code can harm your Mac or compromise your privacy. Be sure you trust the source of build plug-ins before you enable them.`

[Screenshot 1](https://share.cleanshot.com/TjyTZK48)
[Screenshot 2](https://share.cleanshot.com/Bcv3Hwm8)

**Question**
Why does it need access to the keychain? Is this package safe?

**Comment by qeude** [comment]
Hey! Thanks for reporting, I won't have much time to check so anytime soon since I'm into the process of moving from one apartment to another.
But my first guess when seeing those screenshots is that it would come from the SwiftLint plugin that allows Xcode to reformat the code on the go, I think it's worth giving a try updating it, checking issues on their repo and even removing it if there are privacy concern about that package.
To be honest, SwiftDown is something I've made for fun, so I'm not collecting anything and even if I did, it's fully open source so people would know haha, feel free to open a PR if you find something interesting to fix this, I would be happy to approve it 🙏

**Comment by Kinark** [comment]
@sergpryimachuk very curious how you came to a open source project to question it's privacy politics when you could literally check the source code (open source meaning).

**Comment by sergpryimachuk** [comment]
> Hey! Thanks for reporting, I won't have much time to check so anytime soon since I'm into the process of moving from one apartment to another.
> 
> But my first guess when seeing those screenshots is that it would come from the SwiftLint plugin that allows Xcode to reformat the code on the go, I think it's worth giving a try updating it, checking issues on their repo and even removing it if there are privacy concern about that package.
> 
> To be honest, SwiftDown is something I've made for fun, so I'm not collecting anything and even if I did, it's fully open source so people would know haha, feel free to open a PR if you find something interesting to fix this, I would be happy to approve it 🙏

Oh I just noticed your reply. I figured out the problem. It has nothing to do with your package but Xcode 😅

Thanks for making this project and sorry for disturbing 🙏

**Comment by sergpryimachuk** [comment]
> @sergpryimachuk very curious how you came to a open source project to question it's privacy politics when you could literally check the source code (open source meaning).

I'm an obscure developer, didn't know much when I opened the issue. So yeah...

But now, I would literally do what you have said👍
