### ISSUE TITLE
Popover and visuals

### ISSUE THREAD

**Issue by ghost** [qeude/SwiftDown#4]
I was taking a look at the package and noticed a weird behavior when typing the text where its plain text before formatting, I was wondering if you knew of any work arounds.

I was also wondering where the popover to insert an emoji was from.

**Comment by qeude** [comment]
Hi,
Yeah I'm aware of that, there's no real workaround since it's actually a limit that I'm facing due to `NSTextStorage` which appear to be slow so I have to debounce on text changing to apply styles.

You can maybe try to remove the `debounce` in [Storage.swift](https://github.com/qeude/SwiftDown/blob/main/Sources/SwiftDown/Storage.swift). 
Feel free to create a pull request if you manage to find a solution to face this slowness of `NSTextStorage`.

The popover to insert an emoji comes from [Rocket](https://matthewpalmer.net/rocket/)

**Comment by ghost** [comment]
> Hi,
> Yeah I'm aware of that, there's no real workaround since it's actually a limit that I'm facing due to `NSTextStorage` which appear to be slow so I have to debounce on text changing to apply styles.
> 
> You can maybe try to remove the `debounce` in [Storage.swift](https://github.com/qeude/SwiftDown/blob/main/Sources/SwiftDown/Storage.swift).
> Feel free to create a pull request if you manage to find a solution to face this slowness of `NSTextStorage`.
> 
> The popover to insert an emoji comes from [Rocket](https://matthewpalmer.net/rocket/)

Thank you!
